- name: install Python
  tags: programming, python
  become: yes
  package:
    update_cache: yes
    name:
      - python2
      - python3
      - python3-impacket
      - python3-pip

- name: install Python venv package (Debian)
  tags: programming, python
  become: yes
  apt:
    update_cache: yes
    name:
      - python3-venv
  when: ansible_os_family == 'Debian'

- name: create Python virtual environments
  tags: programming, python
  become: yes
  pip:
    virtualenv: /opt/venv/ctf
    virtualenv_command: /usr/bin/python3 -m venv
    name:
      - pwntools
      - requests
      - beautifulsoup4
      - pycryptodome
      - scapy
      - paramiko
      - black
